version: '3.7'

volumes:
    prometheus_data: {}
    probe_data: {}
    redis_data: {}

networks:
  back-tier:

services:

  # prometheus:
  #   image: prom/prometheus:v2.39.0
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #     - '--web.console.templates=/usr/share/prometheus/consoles'
  #   ports:
  #     - 9090:9090
  #   links:
  #       - probe:probe
  #   networks:
  #     - back-tier
  #   restart: always

  probe:
    image: szaydel/smbprobe:test
    volumes:
      - ./config/probe.toml:/config/probe.toml
      # - ./config/.secrets.toml:/config/.secrets.toml
    ports:
      - 8000:8000
    networks:
      - back-tier
    environment:
      SMB_MONITOR_PROBE_CONFIGFILE: /config/probe.toml
      SETTINGS_FILE_FOR_DYNACONF: /config/probe.toml
      SMBPROBE_SECRETS__USERS__SAMT: "Racktop1"
      SMBPROBE_SECRETS__USERS__BETAUSER: "beta-password"
      SMBPROBE_SECRETS__USERS__GAMMAUSER: "gamma-password"
    restart: always

  notifier:
    command:
      # - '--alert-on-first-failure=true --consecutive-fails-limit=5'
      - '--consecutive-fails-limit=5'
    image: szaydel/smbprobe-notifier:test
    # depends_on:
    #   - redis
    # ports:
      # - 8000:8000
    networks:
      - back-tier
    environment:
      SMB_MONITOR_PROBE_CONFIGFILE: /config/probe.toml
      SETTINGS_FILE_FOR_DYNACONF: /config/probe.toml
      SMBPROBE_SECRETS__USERS__SAMT: "Racktop1"
      SMBPROBE_SECRETS__USERS__BETAUSER: "beta-password"
      SMBPROBE_SECRETS__USERS__GAMMAUSER: "gamma-password"
    restart: always
    volumes:
      - ./config/probe.toml:/config/probe.toml
      # - ./config/.secrets.toml:/config/.secrets.toml

  redis:
    image: redis:alpine
    networks:
      - back-tier
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data
    # expose:
    #   - 6379

    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://localhost:5514"
    #     syslog-facility: 1
    #     tag: smb-probe
    #     # Possible formats are rfc3164, rfc5424, rfc5424micro
    #     syslog-format: rfc3164