version: '3.7'

volumes:
    prometheus_data: {}
    probe_data: {}

networks:
  back-tier:

services:

  prometheus:
    image: prom/prometheus:v2.39.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
        - probe:probe
    networks:
      - back-tier
    restart: always

  probe:
    image: rts/probe:test
    volumes:
      - ./monitoring/probe.conf:/monitoring/probe.conf
    ports:
      - 8000:8000
    networks:
      - back-tier
    environment:
      SMB_MONITOR_PROBE_PASSWD: Racktop1
      SMB_MONITOR_PROBE_CONFIGFILE: /monitoring/probe.conf
    restart: always
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: "tcp://localhost:5514"
    #     syslog-facility: 1
    #     tag: smb-probe
    #     # Possible formats are rfc3164, rfc5424, rfc5424micro
    #     syslog-format: rfc3164