version: '3.8'

volumes:
    prometheus_data: {}
    probe_data: {}

networks:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.39.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
        - probe:probe
    networks:
      - back-tier
    restart: always

  probe:
    # The value for this variable comes from .github/workflows/test-probe.yml.
    image: ${TEST_IMAGE_TAG}
    depends_on:
      smb:
        condition: service_started
    links:
      - smb
    volumes:
      - ./config/probe.conf:/config/probe.conf
    ports:
      - 8000:8000
    networks:
      - back-tier
    environment:
      TZ: 'UTC'
      PROBE_ACCOUNT_PASSWORD: probepassword
      SMB_MONITOR_PROBE_CONFIGFILE: /config/probe.conf
    restart: always
    command:

  smb:
    image: dperson/samba
    environment:
      TZ: 'UTC'
    networks:
      - back-tier
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    command: '-u "probeuser;probepassword" -s "probe1;/probe1;yes;no;no;probeuser;probeuser;probeuser" -s "probe2;/probe2;yes;no;no;probeuser;probeuser;probeuser" -p -w test.domain'
