version: '3.8'

name: probe-validation

networks:
  default: {}

services:
  probe:
    # The value for this variable comes from .github/workflows/test-probe.yml.
    # While testing locally, be sure to place this variableby exprting it in 
    # your shell before running this stack, or running the end-2-end test 
    # scripts.
    image: ${TEST_IMAGE_TAG}
    depends_on:
      samba:
        condition: service_healthy
    environment:
      TZ: 'UTC'
      PROBE_ACCOUNT_PASSWORD: probepassword
      SMB_MONITOR_PROBE_CONFIGFILE: /config/probe.conf

    links:
      - samba:smb
    networks:
      - default
    ports:
      - 8000:8000

    restart: always
    volumes:
      - ./config/probe.conf:/config/probe.conf

  samba:
    image: ghcr.io/servercontainers/samba
    depends_on:
      volume_tweaks:
        condition: service_completed_successfully
    environment:
      SAMBA_CONF_LOG_LEVEL: 3
      SAMBA_CONF_WORKGROUP: TEST.DOMAIN
      WSDD2_DISABLE: 1
      AVAHI_DISABLE: 1
      GROUP_probes: 1500
      ACCOUNT_probeuser: probepassword
      UID_probeuser: 1000
      GROUPS_probeuser: probes
      SAMBA_VOLUME_CONFIG_probe1: "[probe1]; path=/probe1; valid users = probeuser; guest ok = no; read only = no; browseable = yes; writeable = yes"
      SAMBA_VOLUME_CONFIG_probe2: "[probe2]; path=/probe2; valid users = probeuser; guest ok = no; read only = no; browseable = yes; writeable = yes"

    healthcheck:
      test: ["CMD", "/usr/bin/nc", "-v", "-w2", "-z", "localhost", "445"]
      interval: 4s
      timeout: 2s
      retries: 3
      start_period: 60s
      start_interval: 30s

    networks:
      - default
    restart: always
    volumes:
      - samba_share_probe1:/probe1
      - samba_share_probe2:/probe2

  # This container is a hack of sorts. Its only purpose is to make minor 
  # modifications to the permissions of the SMB test shares. We want to make 
  # sure that the user(s) we create when we configure SAMBA will be able to 
  # access the shares.
  volume_tweaks:
    image: alpine:latest
    command: "/bin/sh -c '/bin/chmod 0775 /probe[12] && /bin/chgrp -R 1500 /probe[12]'"

    restart: on-failure
    volumes:
      - samba_share_probe1:/probe1
      - samba_share_probe2:/probe2

volumes:
  samba_share_probe1: {}
  samba_share_probe2: {}