IOSIZE = 1 << 10
DEFAULT_LOOP_INTERVAL = 5.0  # seconds
DEFAULT_NUM_FILES = 5
DEFAULT_CONFIG_FILE = "probe.conf"
DEFAULT_ALERT_ON_FIRST_FAILURE = False
DEFAULT_CONSECUTIVE_FAILS_LIMIT = 3
DEFAULT_NOTIFICATIONS_LIST_NAME = "notifications"
