name: SMB Probe Docker Containers

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '24 4 * * *'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches:
      - 'topic/**'
      - 'master'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    strategy:
      matrix:
        include:
          - image: ${{ github.repository }} # github.repository as <account>/<repo>
            dockerfile: Dockerfile.probe
          - image: '${{ github.repository }}-notifier'
            dockerfile: Dockerfile.notifier

    name: Build and optionally publish probe and notifier containers
    steps:
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.4.0
        with:
          cosign-release: 'v2.2.3'

      - name: Check install!
        if: github.event_name != 'pull_request'
        run: cosign version

      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.2.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        # Login only when building on the master branch or when manually triggered.
        if: github.ref_name == 'master' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5.5.1
        env:
          IMAGE_STABILITY: ${{ github.ref == 'refs/heads/main' && 'stable' || 'devel' }}
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image }}
          tags: |
            type=ref,prefix=,suffix=,format=short,event=branch
            type=ref,prefix=,suffix=,format=short,event=tag
            type=ref,prefix=,suffix=,format=short,event=pr
            type=raw,prefix=,suffix=,value=${{ env.IMAGE_STABILITY }}
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule
            type=sha,prefix=,suffix=,format=short,event=branch
            type=sha,prefix=,suffix=,format=short,event=tag
            type=sha,prefix=,suffix=,format=short,event=pr

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker images
        id: build-and-push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          # linux/arm64/v8 is necessary to support Apple Silicon
          platforms: linux/amd64,linux/arm64/v8
          # Push only when building on the master branch or when manually triggered.
          push: ${{ github.ref_name == 'master' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the images with cosign using "keyless" signing method. For more 
      # info check out: https://docs.sigstore.dev/cosign/openid_signing
      - name: Sign the images with GitHub OIDC Token
        # Sign only when building on the master branch or when manually triggered.
        if: github.ref_name == 'master' || github.event_name == 'workflow_dispatch'
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          while read -r tag; do cosign sign --yes "${tag}@${DIGEST}"; done <<< "${TAGS}"