name: Docker Image CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image of the SMB probe
      run: docker build -t rts/probe:latest -t rts/probe:$(git rev-parse --short HEAD)
